# Generated by Django 3.0.3 on 2023-06-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario_Bodega',
        ),
    ]
