# Generated by Django 4.2.2 on 2023-06-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_inventario_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_bodega',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
